services:
  - docker

before_install:
- docker build --target test --tag todo_test_image .
- docker build --target production --tag kogoe1/todo_app:latest .

script:
- docker run todo_test_image todo_app/tests/test_view_model.py
- docker run --env-file=.env.test todo_test_image todo_app/tests/test_integration.py
- docker run --env SECRET_KEY=$SECRET_KEY --env STORAGE_TYPE=$STORAGE_TYPE --env MONGO_USERNAME=$MONGO_USERNAME --env MONGO_PASSWORD=$MONGO_PASSWORD --env MONGO_URL=$MONGO_URL --env DEFAULT_DB=test_todo_db todo_test_image todo_app/tests_e2e/test_selenium_mongo.py


# Push production image to dockerhub
language: generic
deploy: 
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: master

