services:
  - docker

before_install:
- docker build --target test --tag todo_test_image .

script:
- docker run todo_test_image tests/test_view_model.py
- docker run todo_test_image tests/test_integrated.py
- docker run todo_test_image tests_e2e/test_selenium.py