services:
  - docker

before_install:
# - docker build --target test --tag todo_test_image .
- docker build --target production --tag kogoe1/todo_app:latest .

script:
# - docker run todo_test_image todo_app/tests/test_view_model.py
# - docker run --env-file=.env.test todo_test_image todo_app/tests/test_integration.py
# - docker run --env SECRET_KEY=$SECRET_KEY --env TRELLO_API_KEY=$TRELLO_API_KEY --env TRELLO_TOKEN=$TRELLO_TOKEN todo_test_image todo_app/tests_e2e/test_selenium.py


# Push production image to dockerhub
language: generic
deploy: 
  skip_cleanup: true
  provider: script
  script: 
    bash docker_push
    docker pull kogoe1/todo_app:latest
    docker login --username=fiifiogoe@yahoo.com --password=$HEROKU_API_KEY registry.heroku.com
    docker tag kogoe1/todo_app:latest registry.heroku.com/todo-app-ex8/web
    docker push registry.heroku.com/todo-app-ex8/web
    heroku container:release web
    heroku open
  on:
    branch: exercise-8

