services:
  - docker

env:
  global:
    - TEST_ENV_VAR: test_env_var

before_script: echo $TEST_ENV_VAR

before_install:
- docker build --target test --tag todo_test_image .

script:
- docker run todo_test_image tests/test_travis_env.py
# - docker run todo_test_image tests/test_view_model.py
# - docker run todo_test_image tests/test_integration.py
# - docker run todo_test_image tests_e2e/test_selenium.py